# Generated by Django 5.2.4 on 2025-08-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_author_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
